# LambdaTest Configuration

# Project and folder configuration
project_id: "01KW07M90JBNXW5ATZ2XW4S78W"
folder_id: "01KW07MA4T7KSG6ES7BWFCFV1Z"

# Test Run configuration
assignee: 3339933
# Replace this with the numeric ID for "Android_Android 12___Pixel 5".
configuration_id: 0

# Test URL for automation
# test_url: "https://demo.lambdatestinternal.com"

# Tunnel configuration (optional)
# tunnel_name: "your_tunnel_name"
