# LambdaTest Configuration

# Project and folder configuration
project_id: "01KW07M90JBNXW5ATZ2XW4S78W"
folder_id: "01KW07MA4T7KSG6ES7BWFCFV1Z"

# Test Run configuration
assignee: 3339933
configuration_id: "Android_Android 12___Pixel 5"

# Test URL for automation
# test_url: "https://demo.lambdatestinternal.com"

# Tunnel configuration (optional)
# tunnel_name: "your_tunnel_name"
